M48
; DRILL file {KiCad (6.0.1-0)} date 2023 January 25, Wednesday 00:16:01
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-25T00:16:01+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X7.7406Y-2.3599
X7.9682Y-2.3599
T2
X6.8642Y-1.5742
X6.8642Y-2.0242
T0
M30
